name: Test Package Import

on: [pull_request]

jobs:
  test-import:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, windows-latest, windows-2022, windows-2019, macos-latest, macos-12]
        python-version: ['3.10', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies - basic
        run: |
          git config --global core.longpaths true
          python -m pip install --upgrade pip
          pip install .

      - name: Test package import - basic
        run: |
          python -c "import piel"
          python -c "import piel.experimental"
          python -c "import piel.visual"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Test package import
        run: |
          python -c "import piel"
          python -c "import piel.experimental"
          python -c "import piel.visual"
